return {
	api = {
		love		= "http://love2d.org/wiki/love",
		audio		= "http://love2d.org/wiki/love.audio",
		event		= "http://love2d.org/wiki/love.event",
		filesystem	= "http://love2d.org/wiki/love.filesystem",
		font		= "http://love2d.org/wiki/love.font",
		graphics	= "http://love2d.org/wiki/love.graphics",
		image		= "http://love2d.org/wiki/love.image",
		joystick	= "http://love2d.org/wiki/love.joystick",
		keyboard	= "http://love2d.org/wiki/love.keyboard",
		math		= "http://love2d.org/wiki/love.math",
		mouse		= "http://love2d.org/wiki/love.mouse",
		physics		= "http://love2d.org/wiki/love.physics",
		sound		= "http://love2d.org/wiki/love.sound",
		system		= "http://love2d.org/wiki/love.system",
		thread		= "http://love2d.org/wiki/love.thread",
		timer		= "http://love2d.org/wiki/love.timer",
		window		= "http://love2d.org/wiki/love.window",
	},
	some_link = "http://google.com",
	screenshot = "style/screenshots/",
}
