-- LÖVE Homepage Luafied
local strings = require "strings"

return {
	styles = { "style.lua", "style2.lua", "style3.lua" },	-- meta tags and script tags not needed in love
	document = {
		{ "inline", id="debug" },
		{ "block", id="main",
			{ "text", id="title", class="block", "LÖVE" },
			{ "list", id="navigation",
				{ "image", class="link", "style/buttons/wiki_button.png" },
				{ "image", class="link", "style/buttons/forum_button.png" },
				{ "image", class="link", "style/buttons/bugs_button.png" },
			},
			{ "text", id="intro", class="block", "Hi there! LÖVE is an *awesome* framework you can use to make 2D games in Lua. It's free, open-source, and works on Windows, Mac OS X and Linux." },
			{ "block", id="download",
				{ "text", id="down_title", class="block", "Download LÖVE 0.9.1" },
				{ "block", id="windows",
					{ "text", "Windows XP+" } ,
					{ "list",
						{ "text", class="link", "32-bit installer" },
						{ "text", class="link", "32-bit zipped" },
						{ "text", class="link", "64-bit installer" },
						{ "text", class="link", "64-bit zipped" },
					},
				},
				{ "block", id="osx",
					{ "text", "Mac OS X 10.6+" },
					{ "list",
						{ "text", class="link", "64-bit zipped" },
					},
				},
				{ "block", id="ubuntu",
					{ "text", "Ubuntu 12.04 & 13.10 & 14.04" },
					{ "list",
						{ "text", class="link", "PPA" },
						{ "text", { "32-bit: ", { class="link", "liblove" }, " . ", { class="link", "love" }, " . ", { class="link", "dbg" } } },
						{ "text", { "64-bit: ", { class="link", "liblove" }, " . ", { class="link", "love" }, " . ", { class="link", "dbg" } } },
					},
				},
				{ "block", id="other",
					{ "text", "Other downloads" },
					{ "list",
						{ "text", class="link", "LÖVE source" },
						{ "text", class="link", "Older Versions" },
					},
				},
			},
			{ "block", id="features",
				{ "block",
					{ "text", class="block", "Open Source" },
					{ "text", "LÖVE is licensed under the liberal zlib/libpng license. This means that:" },
					{ "list",
						{ "text", "It costs nothing." },
						{ "text", "You can use it freely for commercial purposes with no limitations." },
					},
					{ "text", { "The source can be found on ", { class="link", { "Bitbucket" } }, "." } }
					
				},
				{ "block",
					{ "text", class="block", "Community" },
					{ "list",
						{ "text", { "If you get stuck, many friendly people are ready to help you at ", { class="link", "the forums" }, ". Be warned, however, that it sometimes gets too friendly." } },
						{ "text", "People also post their games and projects on the forums, so it's a nice way of exploring what LÖVE can do. Or at least what people choose to use it for." },
						{ "text", "There is also an IRC channel: #love@irc.oftc.net." },
					},
				},
			},
			{ "block", id="examples",
				{ "text", class="block", "Examples" },
				{ "text", "It’s pretty easy to get started with LÖVE, just check out these code snippets." },
				{ "block",
					{ "list",
						{ "block",
							{ "text", "Drawing text" },
							{ "text", class={ "block", "code" },
{ [[function love.draw()
	love.graphics.print("Hello World!", 400, 300)
end]] },
							},
						},
						{ "block",
							{ "text", "Drawing an image" },
							{ "text", class={ "block", "code" },
{ [[function love.load()
	whale = love.graphics.newImage("whale.png")
end

function love.draw()
	love.graphics.draw(whale, 300, 200)
end]] },
							},
						},
						{ "block",
							{ "text", "Playing a sound" },
							{ "text", class={ "block", "code" }, 
{ [[love.load()
	sound = love.audio.newSource("music.ogg")
end

function love.draw()
	love.audio.play(sound)
end]] },
							},
						},
					},
					{ "text", { "Check out some more tutorials on ", { class="link", "the wiki" } , "." } }
				},
				{ "block", id="games",
					{ "text", class="block", "Games" },
					{ "text", "LÖVE has been used for commercial projects, game jams, prototyping, and everything in between. Here are a few examples." },
					{ "list",
						{ "image", class="link", strings.screenshot.."mr_rescue.png" },
						{ "image", class="link", strings.screenshot.."mari0.png" },
						{ "image", class="link", strings.screenshot.."concerned_joe.png" },
						{ "image", class="link", strings.screenshot.."hexapod_defense_force.png" },
						{ "image", class="link", strings.screenshot.."snayke.png" },
						{ "image", class="link", strings.screenshot.."hawkthorne.png" },
					},
				},
			},
			{ "block", id="footer",
				{ "block", id="stuff",
					{ "text", class="block", "Stuff" },
					{ "list",
						{ "text", class="link", "@obey_love on Twitter" },
						{ "text", class="link", "LÖVE on Google+" },
						{ "text", class="link", "LÖVE T-shirts, etc" },
						{ "text", class="link", "Special effects edition" },
					},
				},
				{ "block", id="donate",
					{ "text", class="block", "Donate" },
					{ "text", "World domination is ensured with your donation. Thank you!" },
					{ "list",
						{ "image", class="link", "style/paypal.png" },
						{ "image", class="link", "style/flattr.png" },
					},
				},
				{ "image", id="moon", class="block", "style/moon.png" },
				{ "block", id="contact",
					{ "text", class="block", "Contact" },
					{ "text", { "You can ",  { class="link", "file a bug" }, ", ask a question in ", { class="link", "the forums" }, " or ", { class="link", "contact rude" }, " for other stuff." } },
				},
				{ "block", id="documentation",
					{ "text", class="block", "Documentation" },
					{ "list",
						{ "text", class="link", "love" },
						{ "text", class="link", "audio" },
						{ "text", class="link", "event" },
						{ "text", class="link", "filesystem" },
						{ "text", class="link", "font" },
						{ "text", class="link", "graphics" },
						{ "text", class="link", "image" },
						{ "text", class="link", "joystick" },
						{ "text", class="link", "keyboard" },
						{ "text", class="link", "math" },
						{ "text", class="link", "mouse" },
						{ "text", class="link", "physics" },
						{ "text", class="link", "sound" },
						{ "text", class="link", "system" },
						{ "text", class="link", "thread" },
						{ "text", class="link", "timer" },
						{ "text", class="link", "window" },
					},
				},
			},
		},
	},
}
