-- LÖVE Homepage Luafied
local strings = require "strings"

local function web_link(url)
	return function() Signal.emit("web_link", url) end
end

local function special_effects(url)
	return function() Signal.emit("special_effects") end
end

return {
	styles = { "style.lua", "style2.lua", "style3.lua" },	-- meta tags and script tags not needed in love
	document = {
		{ type="inline", id="debug" },
		{ type="block", id="main",
			{ type="text", id="title", class="block", "LÖVE" },
			{ type="list", id="navigation",
				{ type="image", class="link", onclick=web_link(strings.some_link), "style/buttons/wiki_button.png" },
				{ type="image", class="link", onclick=web_link(strings.some_link), "style/buttons/forum_button.png" },
				{ type="image", class="link", onclick=web_link(strings.some_link), "style/buttons/bugs_button.png" },
			},
			{ type="text", id="intro", class="block", "Hi there! LÖVE is an *awesome* framework you can use to make 2D games in Lua. It's free, open-source, and works on Windows, Mac OS X and Linux." },
			{ type="block", id="download",
				{ type="text", id="down_title", class="block", "Download LÖVE 0.9.1" },
				{ type="block", id="windows",
					{ type="text", "Windows XP+" } ,
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.some_link), "32-bit installer" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "32-bit zipped" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "64-bit installer" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "64-bit zipped" },
					},
				},
				{ type="block", id="osx",
					{ type="text", "Mac OS X 10.6+" },
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.some_link), "64-bit zipped" },
					},
				},
				{ type="block", id="ubuntu",
					{ type="text", "Ubuntu 12.04 & 13.10 & 14.04" },
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.some_link), "PPA" },
						{ type="text", { "32-bit: ", { class="link", onclick=web_link(strings.some_link), "liblove" }, " . ", { class="link", onclick=web_link(strings.some_link), "love" }, " . ", { class="link", onclick=web_link(strings.some_link), "dbg" } } },
						{ type="text", { "64-bit: ", { class="link", onclick=web_link(strings.some_link), "liblove" }, " . ", { class="link", onclick=web_link(strings.some_link), "love" }, " . ", { class="link", onclick=web_link(strings.some_link), "dbg" } } },
					},
				},
				{ type="block", id="other",
					{ type="text", "Other downloads" },
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.some_link), "LÖVE source" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "Older Versions" },
					},
				},
			},
			{ type="block", id="features",
				{ type="block",
					{ type="text", class="block", "Open Source" },
					{ type="text", "LÖVE is licensed under the liberal zlib/libpng license. This means that:" },
					{ type="list",
						{ type="text", "It costs nothing." },
						{ type="text", "You can use it freely for commercial purposes with no limitations." },
					},
					{ type="text", { "The source can be found on ", { class="link", onclick=web_link(strings.some_link), { "Bitbucket" } }, "." } }
					
				},
				{ type="block",
					{ type="text", class="block", "Community" },
					{ type="list",
						{ type="text", { "If you get stuck, many friendly people are ready to help you at ", { class="link", onclick=web_link(strings.some_link), "the forums" }, ". Be warned, however, that it sometimes gets too friendly." } },
						{ type="text", "People also post their games and projects on the forums, so it's a nice way of exploring what LÖVE can do. Or at least what people choose to use it for." },
						{ type="text", "There is also an IRC channel: #love@irc.oftc.net." },
					},
				},
			},
			{ type="block", id="examples",
				{ type="text", class="block", "Examples" },
				{ type="text", "It’s pretty easy to get started with LÖVE, just check out these code snippets." },
				{ type="block",
					{ type="list",
						{ type="block",
							{ type="text", "Drawing text" },
							{ type="text", class={ "block", "code" },
{ [[function love.draw()
	love.graphics.print("Hello World!", 400, 300)
end]] },
							},
						},
						{ type="block",
							{ type="text", "Drawing an image" },
							{ type="text", class={ "block", "code" },
{ [[function love.load()
	whale = love.graphics.newImage("whale.png")
end

function love.draw()
	love.graphics.draw(whale, 300, 200)
end]] },
							},
						},
						{ type="block",
							{ type="text", "Playing a sound" },
							{ type="text", class={ "block", "code" }, 
{ [[love.load()
	sound = love.audio.newSource("music.ogg")
end

function love.draw()
	love.audio.play(sound)
end]] },
							},
						},
					},
					{ type="text", { "Check out some more tutorials on ", { class="link", onclick=web_link(strings.some_link), "the wiki" } , "." } }
				},
				{ type="block", id="games",
					{ type="text", class="block", "Games" },
					{ type="text", "LÖVE has been used for commercial projects, game jams, prototyping, and everything in between. Here are a few examples." },
					{ type="list",
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."mr_rescue.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."mari0.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."concerned_joe.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."hexapod_defense_force.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."snayke.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), strings.screenshot.."hawkthorne.png" },
					},
				},
			},
			{ type="block", id="footer",
				{ type="block", id="stuff",
					{ type="text", class="block", "Stuff" },
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.some_link), "@obey_love on Twitter" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "LÖVE on Google+" },
						{ type="text", class="link", onclick=web_link(strings.some_link), "LÖVE T-shirts, etc" },
						{ type="text", class="link", onclick=special_effects(), "Special effects edition" },
					},
				},
				{ type="block", id="donate",
					{ type="text", class="block", "Donate" },
					{ type="text", "World domination is ensured with your donation. Thank you!" },
					{ type="list",
						{ type="image", class="link", onclick=web_link(strings.some_link), "style/paypal.png" },
						{ type="image", class="link", onclick=web_link(strings.some_link), "style/flattr.png" },
					},
				},
				{ type="image", id="moon", class="block", "style/moon.png" },
				{ type="block", id="contact",
					{ type="text", class="block", "Contact" },
					{ type="text", { "You can ",  { class="link", onclick=web_link(strings.some_link), "file a bug" }, ", ask a question in ", { class="link", onclick=web_link(strings.some_link), "the forums" }, " or ", { class="link", onclick=web_link(strings.some_link), "contact rude" }, " for other stuff." } },
				},
				{ type="block", id="documentation",
					{ type="text", class="block", "Documentation" },
					{ type="list",
						{ type="text", class="link", onclick=web_link(strings.api.love), "love" },
						{ type="text", class="link", onclick=web_link(strings.api.audio), "audio" },
						{ type="text", class="link", onclick=web_link(strings.api.event), "event" },
						{ type="text", class="link", onclick=web_link(strings.api.filesystem), "filesystem" },
						{ type="text", class="link", onclick=web_link(strings.api.font), "font" },
						{ type="text", class="link", onclick=web_link(strings.api.graphics), "graphics" },
						{ type="text", class="link", onclick=web_link(strings.api.image), "image" },
						{ type="text", class="link", onclick=web_link(strings.api.joystick), "joystick" },
						{ type="text", class="link", onclick=web_link(strings.api.keyboard), "keyboard" },
						{ type="text", class="link", onclick=web_link(strings.api.math), "math" },
						{ type="text", class="link", onclick=web_link(strings.api.mouse), "mouse" },
						{ type="text", class="link", onclick=web_link(strings.api.physics), "physics" },
						{ type="text", class="link", onclick=web_link(strings.api.sound), "sound" },
						{ type="text", class="link", onclick=web_link(strings.api.system), "system" },
						{ type="text", class="link", onclick=web_link(strings.api.thread) , "thread" },
						{ type="text", class="link", onclick=web_link(strings.api.timer), "timer" },
						{ type="text", class="link", onclick=web_link(strings.api.window), "window" },
					},
				},
			},
		},
	},
}
