return {
    { "element", value=1, class={ "root", "red" }, id="one",
        { "element", value=">1", class={ "red" } },
        { "element", value=">2", class={ "red" } },
        { "element", value=">3", class={ "red" },
            { "element", value=">>1" },
            { "element", value=">>2" },
            { "element", value=">>3" },
        },
        { "element", value=">4" },
        { "element", value=">5" },
    },
    { "element", value=2, class={ "root", "red" },
        { "element" },
        { "element" },
        { "element" },
    },
    { "element", value=3, class={ "root", "red" },
        { "element" },
        { "element" },
        { "element" },
    },
    { "element", value=4, class={ "root" }, id="four",
        { "element" },
        { "element" },
        { "element" },
    },
    { "element", value=5, class={ "root" },
        { "element" },
        { "element" },
        { "element" },
    },
    { "element", value=6, class={ "root" } },
    { "element", value=7 },
}
