return {
    { "inline", value=1, class={ "root", "red" }, id="one",
        { "inline", value=">1", class={ "red" } },
        { "inline", value=">2", class={ "red" } },
        { "inline", value=">3", class={ "red" },
            { "inline", value=">>1" },
            { "inline", value=">>2" },
            { "inline", value=">>3" },
        },
        { "inline", value=">4" },
        { "inline", value=">5" },
    },
    { "inline", value=2, class={ "root", "red" },
        { "inline" },
        { "inline" },
        { "inline" },
    },
    { "inline", value=3, class={ "root", "red" },
        { "inline", class="red" },
        { "inline" },
        { "inline" },
    },
    { "inline", value=4, class={ "root" }, id="four",
        { "inline" },
        { "inline" },
        { "inline" },
    },
    { "inline", value=5, class={ "root" },
        { "inline" },
        { "inline" },
        { "inline" },
    },
    { "inline", value=6, class={ "root" } },
    { "inline", value=7 },
}
