local white = { 255, 255, 255, 255 }
local black = { 0, 0, 0, 255 }

return {
	--background_attachment  = ,
	background_color       = white,
	background_image_color = white,
	--background_path        = ,
	background_position    = { 0, 0 },
	background_repeat      = { true, true },
	--background_size        = ,

	border                     = 0,
	border_bottom              = 0,
	border_bottom_color        = white,
	border_bottom_left_radius  = 0,
	border_bottom_right_radius = 0,
	border_color               = white,
	border_left                = 0,
	border_left_color          = white,
	border_radius              = 0,
	border_right               = 0,
	border_right_color         = white,
	border_top                 = 0,
	border_top_color           = white,
	border_top_left_radius     = 0,
	border_top_right_radius    = 0,
	--box_shadow                 = ,

	bottom         = 0,
	clear          = "both",
	display        = "inline",
	float          = "left",
	height         = "100%",
	left           = 0,
	opacity        = 1,
	overflow       = "visible",
	overflow_x     = "visible",
	overflow_y     = "visible",
	padding        = 0,
	padding_bottom = 0,
	padding_left   = 0,
	padding_right  = 0,
	padding_top    = 0,
	position       = "static",
	right          = 0,
	top            = 0,
	visible        = true,
	width          = "100%",
	vertical_align = "top",

	--align_content   = ,
	--align_items     = ,
	--align_self      = ,
	--flex            = ,
	--flex_basis      = ,
	--flex_direction  = ,
	--flex_flow       = ,
	--flex_grow       = ,
	--flex_shrink     = ,
	--flex_wrap       = ,
	--justify_content = ,
	margin          = 0,
	margin_bottom   = 0,
	margin_left     = 0,
	margin_right    = 0,
	margin_top      = 0,
	max_height      = "100%",
	max_width       = "100%",
	min_height      = 0,
	min_width       = 0,
	--order           = ,

	--direction         = ,
	line_height       = 1,
	--overflow_wrap     = ,
	tab_size          = 4,
	text_align        = "left",
	text_color        = black,
	text_decoration   = "none",
	text_indent       = 0,
	--text_orientation  = ,
	text_shadow       = { 0, 0 },
	text_shadow_color = black,
	--text_transform    = ,
	--white_space       = ,

	--font_path = ,
	font_size = 16,

	--list_style          = ,
	--list_style_image    = ,
	--list_style_position = ,
	--list_style_type     = ,

	--[[ = ,
	@keyframes = ,
	animation = ,
	animation_delay = ,
	animation_direction = ,
	animation_duration = ,
	animation_fill_mode = ,
	animation_iteration_count = ,
	animation_name = ,
	animation_timing_function = ,
	animation_play_state = ,

	transition = ,
	transition_property = ,
	transition_duration = ,
	transition_timing_function = ,
	transition_delay = ,

	backface_visibility = ,
	matrix(n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n) = ,
	rotate(angle, x,y,z) = ,
	scale(x,y,z) = ,
	skew(x-angle,y-angle) = ,
	transform_origin = ,
	translate(x,y,z) = ,
	]]-- = ,

	cursor    = "arrow",
	--ime_mode  = ,
	--nav_down  = ,
	--nav_index = ,
	--nav_left  = ,
	--nav_right = ,
	--nav_up    = ,
	--resize    = ,

	--quotes = ,

	--filter = ,

	--mask      = ,
	--mask_type = ,
}
